### ISSUE TITLE
Does not have dockerfile

### ISSUE THREAD

**Issue by GaProgMan** [GaProgMan/OnionArch#11]
## Description

Users who consume this template will have to create their own dockerfile, should they wish to leverage the Docker container technology.

## Possible Solutions

Create a dockerfile so that anyone who uses the template can instantly run the application, without the need of creating their own.

Create a switch for the template which will optionally exclude the dockerfile when a user uses it to create a new project.

**Comment by GuilhermeMartins10** [comment]
Hi, I can do this!

**Comment by GaProgMan** [comment]
Amazing! Thank you.

I would recommend taking a look at the [dockerfile for DwCheckApi](https://github.com/GaProgMan/dwCheckApi/blob/master/Dockerfile) to get you started, if you like. It's a little old, but should still cover the bases.
